apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasa-data-ingestion
  template:
    metadata:
      labels:
        app: nasa-data-ingestion
    spec:
      containers:
        - name: nasa-data-ingestion
          image: your-dockerhub-username/nasa-data-ingestion:latest
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret_access_key
            - name: S3_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: nasa-config
                  key: bucket_name
---
apiVersion: v1
kind: Service
metadata:
  name: nasa-data-service
spec:
  selector:
    app: nasa-data-ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP