apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasa-data-ingestion
  template:
    metadata:
      labels:
        app: nasa-data-ingestion
    spec:
      containers:
        - name: nasa-data-ingestion
          image: xuepingjing/neo-data-image:latest
          ports:
          - containerPort: 5000
          env:
          - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: s3-bucket-name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: aws-secret-access-key
---
apiVersion: v1
kind: Service
metadata:
  name: nasa-data-ingestion-service
spec:
  selector:
    app: nasa-data-ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer