name: Manual Resource Cleanup

on:
  workflow_dispatch:

permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout

env:
  AWS_REGION: eu-west-3
  AWS_TFSTATES_S3_NAME: neo-githubcicd-terraform-tfstates

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash
            working-directory: ./terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_WORKFLOW_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0

      - name: Terraform Initialize
        run: |
          terraform init -backend-config="bucket=${{ env.AWS_TFSTATES_S3_NAME }}" -backend-config="key=infra.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Destroy - EKS and Resources Cleanup
        run: |
          terraform destroy -auto-approve -input=false

      - name: Confirm Deletion
        run: echo "All resources have been deleted."